# Generated by Django 6.0.5 on 2026-06-12 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('usuarios', '0003_direccionenvio_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cancelado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='usuarios.direccionenvio'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion_texto',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='entregado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_estimada_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], default='tarjeta', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='motivo_cancelacion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='pedido',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(max_length=200)),
                ('producto_imagen', models.URLField(blank=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='usuarios.pedido')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto')),
            ],
            options={
                'verbose_name': 'Item de pedido',
                'verbose_name_plural': 'Items de pedido',
            },
        ),
        migrations.CreateModel(
            name='PedidoTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], max_length=20)),
                ('descripcion', models.CharField(max_length=250)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='usuarios.pedido')),
            ],
            options={
                'verbose_name': 'Evento de pedido',
                'verbose_name_plural': 'Eventos de pedido',
                'ordering': ['creado_en'],
            },
        ),
    ]
