# Generated by Django 6.0.5 on 2026-05-15 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icono', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='productos.categoria')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_original', models.DecimalField(blank=True, decimal_places=2, help_text='Si tiene descuento, precio antes del descuento', max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('imagen_url', models.URLField(blank=True, help_text='URL externa de imagen (alternativa a subir archivo)')),
                ('ventas', models.PositiveIntegerField(default=0, help_text='Contador para popularidad')),
                ('valoracion', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('especificaciones', models.JSONField(blank=True, default=dict, help_text='Ej: {"RAM":"16GB","CPU":"i7"}')),
                ('activo', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.categoria')),
                ('plataformas', models.ManyToManyField(blank=True, related_name='productos', to='productos.plataforma')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'ordering': ['-activo'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, upload_to='productos/galeria/')),
                ('url', models.URLField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='productos.producto')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
